package org.red5.server.common.amf;

public enum AMFType {
	AMF_UNDEFINED,
	AMF_NULL,
	AMF_NUMBER,
	AMF_BOOLEAN,
	AMF_DATE,
	AMF_STRING,
	AMF_ARRAY,
	AMF_XML,
	AMF_OBJECT,
	AMF0_MOVIECLIP,
	AMF0_REFERENCE,
	AMF0_MIXED_ARRAY,
	AMF0_END_OF_OBJECT,
	AMF0_LONG_STRING,
	AMF0_UNSUPPORTED,
	AMF0_RECORDSET,
	AMF0_CLASS_OBJECT,
	AMF3_TRUE,
	AMF3_FALSE,
	AMF3_INTEGER,
	AMF3_XML_DOC,
	AMF3_BYTE_ARRAY
}
